/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      D:/ti/grace/grace_2_20_02_32/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
// extern volatile char incoming_msg[512];
// extern volatile char RXdone;
/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}


/* Interrupt Function Prototypes */

/*
 * ======== Preserved user code snippets ========
 */
#if 0
    /* USER CODE START (section: USCI0RX_ISR_HOOK) */
    // static unsigned int i = 0;
    // if (IFG2 & UCA0RXIFG)
    // {
    //     // incoming_msg[i] = UCA0RXBUF; // Read received byte
    //     if (UCA0RXBUF == 0x0A || i == 511) 
    //     {
    //         i = 0;
    //         RXdone = 'Y';
    //     }
    //     else 
    //     {
    //         i++;
    //     }
    //     IFG2 &= ~UCA0RXIFG;
    // }
    /* USER CODE END (section: USCI0RX_ISR_HOOK) */
#endif
